input_variables:
- context
output_parser: null
template: '
Design an experiment with the following details based on the following
 context given, delimited by triple backticks. 

```{context}``` 

problem: <One liner summarising the problem the client wants solved> 
sample: <What is the sample of interest> 
model_type: ["classification", "regression", "others"] 
target_labels: <List of classes if classification, or a string describing the target output if regression>
current_methodologies: <Current methodologies to quantify the problem> 
sample_state: ["Solid", "Liquid"] 
sample_nature: <Identify the closest category out of the list provided: ["Solutions & Colloids", 
"Suspensions & Slurries", "Fine powders", "Coarse powders", "Solid particles", "Semi-solids"]> 
n_samples: <Integer number per class if classification (at least 10 per class), or Single integer number if regression (at least 30)> 

Return the output in JSON format.
'
template_format: f-string