defaults:
  - _self_
  - embeddings: all-mpnet-base-v2
  - llm: text-davinci-003
  - vectorstore: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
